[build]
functions = "functions"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "https://cute-pithivier-8b373e.netlify.app/api/:splat"
  signed = "JWT_SEC"
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"