[build]
functions = "functions"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions"
  signed = "JWT_SEC"
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"