import { Application } from "express";
const authRouter = require("./auth");
const eventRouter = require("./event");
const showTimeRouter = require("./showTime");
const ticketRouter = require("./ticket");
const addressRouter = require("./address");
const myRouter = require("./my");
const paymentRouter = require("./payment");
const discountRouter = require("./discount");
const userRouter = require("./user");
const chartRouter = require("./chart");
const imageRouter = require("./image");
const bookingRouter = require("./booking");
const stageRouter = require("./stage");
function Routes(app: Application, path:String) {
  app.use(`${path}`, authRouter);
  app.use(`${path}/event`, eventRouter);
  app.use(`${path}/showtime`, showTimeRouter);
  app.use(`${path}/ticket`, ticketRouter);
  app.use(`${path}/address`, addressRouter);
  app.use(`${path}/my`, myRouter);
  app.use(`${path}/payment`, paymentRouter);
  app.use(`${path}/discount`, discountRouter);
  app.use(`${path}/user`, userRouter);
  app.use(`${path}/chart`, chartRouter);
  app.use(`${path}/image`, imageRouter);
  app.use(`${path}/stage`, stageRouter);
  app.use(`${path}/booking`, bookingRouter);
}
module.exports = Routes;
